  version: '3'
  services:
    ebbinghaus-memory-telegram-bot:
      build: ${BUILD_PATH}
      image: ebbinghaus-memory-bot
      container_name: ebbinghaus-memory-bot
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      volumes:
        - local:/var/lib/ebbinghaus-memory-bot/
      environment:
        DB_HOST: postgres_emtb
        DB_NAME: ${EMTB_DB_NAME}
        DB_USERNAME: ${EMTB_DB_USERNAME}
        DB_PASSWORD: ${EMTB_DB_PASSWORD}
        BOT_TOKEN: ${EMTB_BOT_TOKEN}
        BOT_NAME: ${EMTB_BOT_NAME}
        BOT_OWNER: ${EMTB_BOT_OWNER}
        APP_PORT: ${EMTB_APP_PORT}
        JAVA_TOOL_OPTIONS: ${EMTB_JAVA_OPTS}
        LOKI_URL: ${LOKI_URL}
        ACTUATOR_USER: ${ACTUATOR_USER}
        ACTUATOR_PASSWORD: ${ACTUATOR_PASSWORD}
        APPLICATION_LOG_APPENDER: ${APPLICATION_LOG_APPENDER}
        AI_API_KEY: ${AI_API_KEY}
      ports:
        - ${EMTB_APP_EXTERNAL_PORT}:${EMTB_APP_PORT}
      networks:
        - emtb
      restart: on-failure
      depends_on:
        - postgres_emtb
    postgres_emtb:
      container_name: postgres_emtb
      image: postgres:16
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${EMTB_DB_NAME}
        POSTGRES_USER: ${EMTB_DB_USERNAME}
        POSTGRES_PASSWORD: ${EMTB_DB_PASSWORD}
      ports:
        - 127.0.0.1:${DB_EMTB_EXTERNAL_PORT}:5432
      networks:
        - emtb
      restart: unless-stopped
    postgres_emtb_backup:
      image: prodrigestivill/postgres-backup-local:latest
      container_name: postgres_emtb_backup
      depends_on:
        - postgres_emtb
      networks:
        - emtb
      restart: unless-stopped
      environment:
        TZ: Europe/Warsaw
        POSTGRES_HOST: postgres_emtb
        POSTGRES_DB: ${EMTB_DB_NAME}
        POSTGRES_USER: ${EMTB_DB_USERNAME}
        POSTGRES_PASSWORD: ${EMTB_DB_PASSWORD}
        SCHEDULE: "0 2 * * *"
        BACKUP_KEEP_DAYS: "2"
        BACKUP_KEEP_WEEKS: "0"
        BACKUP_KEEP_MONTHS: "0"
        BACKUP_ON_START: "FALSE"
      volumes:
        - /root/backups/postgres/mmr_bt:/backups
  volumes:
    postgres_data:
      driver: local
    local:
      driver: local

  networks:
    emtb:
      driver: bridge