spring:
  application:
    name: ebbinghaus-memory-telegram-app
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?currentSchema=memorybot
  ai:
    openai:
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}
          response-format: json_object
  flyway:
    schemas:
      - memorybot
    baseline-on-migrate: true
    locations: classpath:scripts
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: false
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          threadPool:
            threadCount: 5
bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
  owner: ${BOT_OWNER}
server:
  port: ${APP_PORT:8081}
app:
  max:
    try-fibonacci-time: 55