package com.ebbinghaus.memory.app.model;

public enum UserState {
  FIRST_TIME_MENU,
  MAIN_MENU,
  WAIT_TEXT,
  WAIT_FORWARDED_MESSAGE,
  WAIT_EDIT_TEXT_CONCRETE,
  WAIT_EDIT_TEXT,
  SHORT_MESSAGE,
  DATA_LIST,
  PROFILE,
  HELP,
  CATEGORY_DATA_LIST,
  MESSAGES_INVALID_INPUT,
  DEFAULT
}
